---
- name: Install distro packages
  package:
    name: "{{ memcached_distro_packages }}"
    state: "{{ memcached_package_state }}"
  notify: Restart memcached
  register: install_packages
  until: install_packages is success
  retries: 5
  delay: 2

