---
- name: Make sure libvirt is started
  service:
    name: "libvirtd"
    state: "started"
  when: inventory_hostname in groups['nova-compute']

## Ceph nova client libvirt secret
- name: Retrieve nova secret from cephcluster
  command: ceph auth get-key client.{{ nova_ceph_client }}
  when:
    - inventory_hostname in groups['nova-compute']
  changed_when: false
  delegate_to: '{{ ceph_mon_host[0] }}'
  register: ceph_nova_secret

- name: Check if nova secret is defined in libvirt
  shell: virsh secret-list|grep {{ nova_ceph_client_uuid }}
  when:
    - inventory_hostname in groups['nova-compute']
  changed_when: false
  failed_when:  false
  register: libvirt_nova_defined

- name: Provide xml file to create the secret
  template:
    src: secret.xml.j2
    dest: /tmp/nova-secret.xml
    mode: "0600"
  with_items:
    - secret_uuid: "{{ nova_ceph_client_uuid }}"
      client_name: "{{ nova_ceph_client }}"
  when:
    - inventory_hostname in groups['nova-compute']
    - libvirt_nova_defined.rc is defined
    - libvirt_nova_defined.rc != 0

- name: Define libvirt nova secret
  command: virsh secret-define --file /tmp/nova-secret.xml
  when:
    - inventory_hostname in groups['nova-compute']
    - libvirt_nova_defined.rc is defined
    - libvirt_nova_defined.rc != 0
  notify:
    - Restart os services

- name: Check if nova secret value is set in libvirt
  command: virsh secret-get-value {{ nova_ceph_client_uuid }}
  when:
    - inventory_hostname in groups['nova-compute']
  changed_when: false
  failed_when:  false
  register: libvirt_nova_set

- name: Set nova secret value in libvirt
  command: virsh secret-set-value --secret {{ nova_ceph_client_uuid }} --base64 {{ ceph_nova_secret.stdout }}
  changed_when: false
  when:
    - inventory_hostname in groups['nova-compute']
    - libvirt_nova_set.rc is defined
    - libvirt_nova_set.rc != 0 or
      (libvirt_nova_set.rc == 0 and
       libvirt_nova_set.stdout != ceph_nova_secret.stdout)
  notify:
    - Restart os services

- name: Remove libvirt nova secret file
  file:
    path: "/tmp/nova-secret.xml"
    state: "absent"
  when:
    - inventory_hostname in groups['nova-compute'] and libvirt_nova_set
