---
- name: Install ceph packages
  package:
    name: '{{ ceph_client_filtered_packages }}'
    state: "{{ ceph_client_package_state }}"
  register: install_packages
  until: install_packages is success
  retries: 5
  delay: 2
  notify:
    - Restart os services
