---
- name: Provide ceph configuration directory
  file:
    dest: /etc/ceph
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Set ceph_mon_host facts
  set_fact:
    ceph_mon_host: |
      {% set mon_ip = [] %}
      {% for comp in az_cephmon_compose %}
      {%   if comp.availability_zone == hostvars[inventory_hostname]['availability_zone'] %}
      {%     set _ = mon_ip.append(comp.ceph_mon_host) %}
      {%   endif %}
      {% endfor %}
      {{ mon_ip }}

- name: Get ceph.conf and store contents when ceph_conf_file is not defined
  slurp:
    src: /etc/ceph/ceph.conf
  register: ceph_conf_content_mon
  delegate_to: '{{ ceph_mon_host[0] }}'
  changed_when: false
  when:
    - ceph_conf_file is not defined

- name: Register ceph_conf fact when ceph_conf_file is not defined
  set_fact:
    ceph_conf: "{{ ceph_conf_content_mon.content | b64decode }}"
  when:
    - ceph_conf_file is not defined

- name: Register ceph_conf fact when ceph_conf_file is defined
  set_fact:
    ceph_conf: "{{ ceph_conf_file }}\n\n"
  when:
    - ceph_conf_file is defined

- name: Create ceph.conf from mon host
  copy:
    content: '{{ ceph_conf }}'
    dest: /etc/ceph/ceph.conf
    owner:  root
    group:  root
    mode:   0644
  notify:
    - Restart os services

#TODO: also be able to create users, keys and pools on ceph
- name: Retrieve keyrings for openstack clients from ceph cluster
  # the first get makes sure the client exists, so the second only runs when it
  # exists, the trick is the different output of both, the second has the right
  # output to put in a keyring; ceph admin should have already created the user
  shell: ceph auth get client.{{ item }} >/dev/null && ceph auth get-or-create client.{{ item }}
  with_items: "{{ ceph_client_filtered_clients }}"
  changed_when: false
  delegate_to: '{{ ceph_mon_host[0] }}'
  register: ceph_client_keyrings
  until: ceph_client_keyrings is success
  retries: 3

- name: Provision ceph client keyrings
  # TODO: do we really need a template for this? what's the added value compare to
  # ceph get-or-create ... ... -o file?
  template:
    src:      ceph.client.keyring.j2
    dest:     /etc/ceph/ceph.client.{{ item.item }}.keyring
    backup:   true
    mode:     0644
  with_items: "{{ ceph_client_keyrings.results }}"
  when:
    - item is not skipped
  notify:
    - Restart os services
