---
- name: Create openrc file
  template:
    src: openrc.j2
    dest: "{{ openrc_file_dest }}"
    owner: "{{ openrc_file_owner }}"
    group: "{{ openrc_file_group }}"
    mode: "{{ openrc_file_mode }}"

- name: Create OpenStack client configuration directory
  file:
    dest: "{{ openrc_openstack_client_config_dir_dest }}"
    owner: "{{ openrc_openstack_client_config_dir_owner }}"
    group: "{{ openrc_openstack_client_config_dir_group }}"
    mode: "{{ openrc_openstack_client_config_dir_mode }}"
    state: directory

- name: Create clouds.yaml file
  template:
    src: clouds.yaml.j2
    dest: "{{ openrc_clouds_yml_file_dest }}"
    owner: "{{ openrc_clouds_yml_file_owner }}"
    group: "{{ openrc_clouds_yml_file_group }}"
    mode: "{{ openrc_clouds_yml_file_mode }}"
