---
- name: Check if credential keys already exist
  stat:
    path: "{{ keystone_credential_tokens_key_repository }}/0"
  register: _credential_keys

- name: Create credential keys for Keystone
  command: >
    {{ keystone_bin }}/keystone-manage credential_setup
                                       --keystone-user "{{ keystone_system_user_name }}"
                                       --keystone-group "{{ keystone_system_group_name }}"
  become: yes
  become_user: "{{ keystone_system_user_name }}"
  when: not _credential_keys.stat.exists

- name: Rotate credential keys for Keystone
  command: >
    {{ keystone_bin }}/keystone-manage credential_rotate
                                       --keystone-user "{{ keystone_system_user_name }}"
                                       --keystone-group "{{ keystone_system_group_name }}"
  become: yes
  become_user: "{{ keystone_system_user_name }}"
  when: _credential_keys.stat.exists

- name: Distribute the credential key repository
  command: >
    rsync -e 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
          -avz
          --delete
          {{ keystone_credential_tokens_key_repository }}/
          {{ keystone_system_user_name }}@{{ hostvars[item]['ansible_host'] }}:{{ keystone_credential_tokens_key_repository }}/
  become: yes
  become_user: "{{ keystone_system_user_name }}"
  changed_when: false
  with_items: "{{ groups['keystone'][1:] }}"
  tags:
    - skip_ansible_lint

- name: Drop credential key auto rotate script
  template:
    src: "keystone-credential-rotate.sh.j2"
    dest: "{{ keystone_credential_auto_rotation_script }}"
    owner: "{{ keystone_system_user_name }}"
    group: "{{ keystone_system_group_name }}"
    mode: "0755"

# This creates the auto rotation job on the first keystone host.
- name: Create auto rotation job
  cron:
    name: "Fernet auto rotate job"
    special_time: "{{ keystone_credential_rotation }}"
    user: "{{ keystone_system_user_name }}"
    job: "{{ keystone_credential_auto_rotation_script }}"
    cron_file: keystone-credential-rotate
  when: >
    inventory_hostname == groups['keystone'][0]

# This makes sure that no auto rotation jobs are on any other hosts.
- name: Remove extra auto rotation job
  cron:
    name: "Fernet auto rotate job"
    cron_file: keystone-credential-rotate
    state: "absent"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['keystone'][1:] }}"
