---
- name: Copying over common neutron conf
  merge_configs:
    sources:
      - "{{ role_path }}/templates/{{ item.src }}.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/{{ item.src }}"
      - "{{ node_custom_config }}/neutron/{{ item.src }}"
      - "{{ node_custom_config }}/neutron/{{ inventory_hostname }}/{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0666"
  become: true
  with_items:
    - src: "neutron.conf"
      dest: "{{ neutron_conf_dir }}/neutron.conf"
    - src: "{{ neutron_plugins[neutron_plugin_type].plugin_ini }}"
      dest: "{{ neutron_conf_dir }}/{{ neutron_plugins[neutron_plugin_type].plugin_ini }}"
  notify:
    - Restart neutron services

- name: Copying over neutron_lbaas.conf
  merge_configs:
    sources:
      - "{{ role_path }}/templates/neutron_lbaas.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/neutron_lbaas.conf"
      - "{{ node_custom_config }}/neutron/neutron_lbaas.conf"
      - "{{ node_custom_config }}/neutron/{{ inventory_hostname }}/neutron_lbaas.conf"
    dest: "/etc/neutron/neutron_lbaas.conf"
    mode: "0666"
  become: true
  notify:
    - Restart neutron services

- name: Copying over api-paste.ini
  template:
    src: "{{ item }}"
    dest: "/etc/neutron/api-paste.ini"
    owner: root
    group: "{{ neutron_system_user_name }}"
    mode: "0660"
  with_first_found:
    - "{{ node_custom_config }}/neutron/api-paste.ini"
    - "api-paste.ini.j2"
  notify:
    - Restart neutron services

- name: Copy neutron ml2 plugin config
  template:
    src: "{{ neutron_plugins[item].plugin_ini }}.j2"
    dest: "{{ neutron_conf_dir }}/{{ neutron_plugins[item].plugin_ini }}"
    owner: "root"
    group: "{{ neutron_system_group_name }}"
    mode: "0640"
  with_items: "{{ neutron_plugin_types }}"
  when: "'plugin_ini' in neutron_plugins[item]"
  notify:
    - Restart neutron services

- name: Copying over terra.ini
  template:
    src: "{{ item }}"
    dest: "/etc/neutron/terra.ini"
    owner: root
    group: "{{ neutron_system_user_name }}"
    mode: "0660"
  with_first_found:
    - "{{ node_custom_config }}/neutron/terra.ini"
    - "terra.ini.j2"
  notify:
    - Restart neutron services

- name: Create plugin.ini file link
  file:
    src: /etc/neutron/plugins/ml2/ml2_conf.ini
    dest: /etc/neutron/plugin.ini
    state: link
  notify:
    - Restart neutron services

- name: Generate neutron agent only Config
  template:
    src: "{{ item.service_conf }}.j2"
    dest: "{{ item.service_conf_path }}/{{ item.service_conf }}"
    owner: "root"
    group: "{{ neutron_system_group_name }}"
    mode: "0640"
  with_items: "{{ filtered_neutron_services }}"
  notify:
    - Restart neutron services
  when:
    - "'service_conf_path' in item"
    - "'service_conf' in item"
