---
- name: Create the system group
  group:
    name: "{{ neutron_system_group_name }}"
    state: "present"
    system: "yes"

- name: Create the neutron system user
  user:
    name: "{{ neutron_system_user_name }}"
    group: "{{ neutron_system_group_name }}"
    comment: "{{ neutron_system_comment }}"
    shell: "{{ neutron_system_shell }}"
    system: "yes"
    createhome: "yes"
    home: "/var/lib/{{ neutron_system_user_name }}"

- name: Create neutron dir
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner|default(neutron_system_user_name) }}"
    group: "{{ item.group|default(neutron_system_group_name) }}"
    mode: "{{ item.mode | default(omit) }}"
  with_items:
    - { path: "{{ neutron_conf_dir }}", mode: "0750" }
    - { path: "{{ neutron_conf_dir }}/plugins", mode: "0750" }
    - { path: "{{ neutron_conf_dir }}/plugins/{{ neutron_plugin_type.split('.')[0] }}", mode: "0750" }
    - { path: "{{ neutron_lock_path }}" }
    - { path: "/var/run/neutron" }
    - { path: "{{ neutron_system_home_folder }}", mode: "0755" }
    - { path: "{{ neutron_system_home_folder }}/ha_confs" }
    - { path: "{{ neutron_log_dir }}" }
