---
# Copyright 2020 weimeng <weim6@chinaunicom.cn>
- include_tasks: port_checks.yml

- include_tasks: service_checks.yml

- include_tasks: package_checks.yml

- include_tasks: nvidia_checks.yml
  when: "gpu_server_type is defined"

- include_tasks: user_checks.yml
