---
- name: Ensure rabbitmq package is installed
  yum:
    name: "{{ rabbitmq_package_name }}"
    state: "{{ rabbitmq_package_state }}"
  register: rabbitmq_install
  until: rabbitmq_install is success
  retries: 3
  delay: 2
  notify: Restart rabbitmq server (ALL)

- name: Create rabbitmq config
  register: rabbit_config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "rabbitmq.config.j2", dest: "/etc/rabbitmq/rabbitmq.config" }
    - { src: "rabbitmq-server.j2", dest: "/etc/default/rabbitmq-server" }
    - { src: "rabbitmq-env.j2", dest: "/etc/rabbitmq/rabbitmq-env.conf" }
  notify: Restart rabbitmq server (ALL)

- name: Set rabbit cookie
  copy:
    content: "{{ rabbitmq_cookie_token }}"
    dest: /var/lib/rabbitmq/.erlang.cookie
    mode: "0400"
    owner: rabbitmq
    group: rabbitmq
  notify: Restart rabbitmq server (ALL)
