---
- name: Get CPU info content and store as var
  command: cat /proc/cpuinfo
  register: cpuinfo_contents
  changed_when: false
  when:
    - nova_virt_type is not defined

- name: Register a fact for the nova kvm virt type
  set_fact:
    nova_virt_type: "kvm"
  when:
    - nova_virt_type is not defined
    - cpuinfo_contents.stdout.find('vmx') != -1
      or cpuinfo_contents.stdout.find('svm') != -1
      or cpuinfo_contents.stdout.find('PowerNV') != -1
      or (cpuinfo_contents.stdout.find('pSeries') != -1
          and cpuinfo_contents.stdout.find('qemu') != -1
          and ansible_architecture == 'ppc64le')
      or ansible_architecture == 'aarch64'

- name: Register a fact for the nova powervm virt type
  set_fact:
    nova_virt_type: "powervm"
  when:
    - nova_virt_type is not defined
    - cpuinfo_contents.stdout.find('pSeries') != -1
    - ansible_architecture == 'ppc64le'
    - cpuinfo_contents.stdout.find('qemu') == -1

- name: Register a fact for the nova qemu virt type
  set_fact:
    nova_virt_type: "qemu"
  when:
    - nova_virt_type is not defined
