---
- name: Create haproxy systemd service config dir
  file:
    path: "/etc/systemd/system/haproxy.service.d"
    state: "directory"
    group: "root"
    owner: "root"
    mode: "0755"

- name: Apply systemd options
  template:
    src: "{{ item.src }}"
    dest: "/etc/systemd/system/haproxy.service.d/{{ item.dest }}"
    mode: "0644"
  with_items:
    - { src: "systemd.limits.conf.j2", dest: "limits.conf" }
  notify: Restart haproxy service

- name: Reload systemd service files
  systemd:
    daemon_reload: yes

- name: Drop haproxy logrotate config
  template:
    src: "logrotate-haproxy.cfg"
    dest: "/etc/logrotate.d/haproxy"

- name: Make haproxy bindable on non local addresses
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: 1
    sysctl_set: yes
    state: present
  when: haproxy_bind_on_non_local | bool

- name: Drop haproxy logging config
  template:
    src: "haproxy-logging.cfg"
    dest: "/etc/rsyslog.d/99-haproxy-local-logging.conf"
  notify: Restart rsyslog
