---
- name: Ensure chrony package is exist
  package:
    name: chrony
    state: present
  notify: Restart chrony service

- name: Copy over chrony config file
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
  notify: Restart chrony service

- name: Ensure chronyd serivce is running
  service:
    name: chronyd
    state: started
    enabled: yes
