---
- name: Create DB for service
  mysql_db:
    login_user: "{{ galera_root_user }}"
    login_password: "{{ galera_root_password }}"
    login_host: "{{ database_address }}"
    name: "{{ cinder_database_name }}"
    state: "present"
  delegate_to: "{{ cinder_db_setup_host }}"
  no_log: True

- name: Grant access to the DB for the service
  mysql_user:
    login_user: "{{ galera_root_user }}"
    login_password: "{{ galera_root_password }}"
    login_host: "{{ database_address }}"
    name: "{{ cinder_database_name }}"
    password: "{{ cinder_database_password }}"
    host: "{{ item }}"
    state: "present"
    priv: "{{ cinder_database_name }}.*:ALL"
  delegate_to: "{{ cinder_db_setup_host }}"
  with_items:
    - "localhost"
    - "%"
  no_log: True

- name: Perform a Cinder DB sync
  command: "{{ cinder_bin }}/cinder-manage db sync"
  become: yes
  become_user: "{{ cinder_system_user_name }}"
  changed_when: false
