---
- name: Restart libvirtd services
  systemd:
    name: "{{ libvirt_service_name }}"
    enabled: yes
    daemon_reload: true
    state: restarted
  when: nova_services['nova-compute']['group'] in group_names

- name: Restart nova services
  systemd:
    name: "{{ item.service_name }}"
    enabled: yes
    state: "restarted"
    daemon_reload: yes
  with_items: "{{ filtered_nova_services }}"

- name: Restart httpd service (placement-api)
  service:
    name: httpd
    state: "restarted"
    enabled: yes

- name: Restart haproxy service
  service:
    name: haproxy
    state: restarted
    enabled: true
