---
- name: Whether there is a dims block device
  command: "rbd info dims-{{ ansible_hostname }} -p volumes -k /etc/ceph/ceph.client.cinder.keyring -n client.cinder"
  become: yes
  changed_when: false
  ignore_errors: yes
  register: rbd_device_info

- name: Create rbd device for dimsagent
  command: "rbd create dims-{{ ansible_hostname }} -p volumes --size 500G -k /etc/ceph/ceph.client.cinder.keyring -n client.cinder"
  become: yes
  changed_when: false
  when: rbd_device_info.rc != 0

- name: Drop rbd-mount auto script
  template:
    src: "rbd-mount.sh.j2"
    dest: "/usr/local/bin/rbd-mount"
    owner: "root"
    group: "root"
    mode: "0755"
  notify:
    - Restart rbd-mount service

- name: Copying over rbd-mount service files
  copy:
    src: "{{ item }}"
    dest: "/usr/lib/systemd/system/{{ item }}"
    mode: "0660"
  become: true
  with_items:
    - rbd-mount.service
  notify:
    - Restart rbd-mount service
