---
# Set the package install state for distribution packages
# Options are 'present' and 'latest'
rabbitmq_package_state: "present"

rabbitmq_package_name:
  - openssl
  - rabbitmq-server

# Inventory group containing the hosts for the cluster
rabbitmq_host_group: "rabbitmq"

# The local address used for the rabbitmq cluster node
rabbitmq_node_address: "{{ ansible_host }}"

# Hosts file entries (set this to an empty list to disable /etc/hosts generation
# for the rabbitmq cluster nodes)
rabbitmq_hosts_entries: |-
  {% set _var = [] %}
  {% for cluster_host in groups[rabbitmq_host_group] %}
  {%   set _addr = hostvars[cluster_host]['rabbitmq_node_address'] |
                   default(hostvars[cluster_host]['ansible_host']) %}
  {%   set _hostnames = [
         cluster_host,
         cluster_host.split('.')[0]
       ]
  %}
  {%   set _ = _var.append({'address': _addr, 'hostnames': _hostnames}) %}
  {% endfor %}
  {{ _var }}

rabbitmq_primary_cluster_node: "{{ hostvars[groups[rabbitmq_host_group][0]]['ansible_fqdn'] }}"

# Name of the rabbitmq cluster
rabbitmq_cluster_name: rabbitmq_cluster1

# Specify a partition recovery strategy (autoheal | pause_minority | ignore)
rabbitmq_cluster_partition_handling: pause_minority

# Rabbitmq open file limits
rabbitmq_ulimit: 65536

rabbitmq_cookie_token: securet

# Configure rabbitmq plugins
rabbitmq_plugins:
  - name: rabbitmq_management
    state: enabled

# RabbitMQ erlang VM parameters
rabbitmq_async_threads: 128
rabbitmq_process_limit: 1048576

# RabbitMQ collect statistics interval
rabbitmq_collect_statistics_interval: 5000

# RabbitMQ Management rates mode
rabbitmq_management_rates_mode: basic

# Precompile RabbitMQ with HiPE
rabbitmq_hipe_compile: False

# Disable non-TLS listeners
rabbitmq_disable_non_tls_listeners: False

# RabbitMQ policies
# Used to tune performance characteristics of OpenStack messaging
#
# Example override that uses HA queues only for telemetry and sets message
# expiry for RPC messages
#
# rabbitmq_policies:
#   - name: "heat_rpc_expire"
#     pattern: '^heat-engine-listener\\.'
#     tags: "expires=3600000"
#     priority: 1
#   - name: "results_expire"
#     pattern: '^results\\.'
#     tags: "expires=3600000"
#     priority: 1
#   - name: "tasks_expire"
#     pattern: '^results\\.'
#     tags: "expires=3600000"
#     priority: 1
#   - name: "ha-notif"
#     pattern: '^(event|metering|notifications)\.'
#     tags: "ha-sync-mode=automatic"
#     priority: 0
#
rabbitmq_policies:
  - name: "HA"
    pattern: '^(?!amq\.).*'
    tags: "ha-mode=all"

# Openstack Rabbitmq User
oslomsg_openstack_vhost: /
oslomsg_openstack_user: openstack
